Prefix(:=<http://www.ease-crc.org/ont/SOMA_DFL.owl#>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
Prefix(dul:=<http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>)
Prefix(soma:=<http://www.ease-crc.org/ont/SOMA.owl#>)


Ontology(<http://www.ease-crc.org/ont/SOMA_DFL.owl>
Import(<file://./SOMA.owl>)

############################
#   Classes
############################


SubClassOf(:Actor1 :Actor)
SubClassOf(:Actor2 :Actor)
SubClassOf(:Actor :Agent)
EquivalentClasses(:Agent soma:AgentRole)
SubClassOf(:Asset soma:ResourceRole)
SubClassOf(:Attribute soma:EventAdjacentRole)
EquivalentClasses(:Beneficiary soma:BeneficiaryRole)
SubClassOf(:Cause soma:CausativeRole)
EquivalentClasses(:Destination soma:Destination)
EquivalentClasses(:Experiencer soma:ExperiencerRole)
EquivalentClasses(:Instrument soma:Instrument)
EquivalentClasses(:Location soma:Location)
SubClassOf(:Material soma:EventAdjacentRole)
SubClassOf(:Patient1 :Patient)
SubClassOf(:Patient2 :Patient)
EquivalentClasses(:Patient soma:Patient)
SubClassOf(:Predicate soma:EventAdjacentRole)
EquivalentClasses(:Product soma:ResultRole)
EquivalentClasses(:Recipient soma:RecipientRole)
EquivalentClasses(:Source soma:Origin)
SubClassOf(:Stimulus soma:StimulusRole)
SubClassOf(:Theme1 :Theme)
SubClassOf(:Theme2 :Theme)
SubClassOf(:Theme soma:EventAdjacentRole)
EquivalentClasses(:Topic soma:CommunicationTopic)

SubClassOf(:body_part.n.wn.anatomy dul:BiologicalObject)
SubClassOf(:chordate.n.wn.animal dul:Organism)
SubClassOf(:domestic_animal.n.wn.animal dul:Organism)
SubClassOf(:fabric.n.wn.artifact dul:DesignedArtifact)
SubClassOf(:food.n.wn.food dul:PhysicalObject)
SubClassOf(:instrumentality.n.wn.artifact dul:DesignedArtifact)
SubClassOf(:mammal.n.wn.animal dul:Organism)
EquivalentClasses(:part.n.wn.artifact soma:FunctionalPart)
SubClassOf(:object.n.wn.object dul:PhysicalObject)
SubClassOf(:person.n.wn.body dul:NaturalPerson)
SubClassOf(:plant.n.wn.botany dul:Organism)
SubClassOf(:plant_part.n.wn.plant dul:BiologicalObject)
SubClassOf(:region.n.wn.location dul:PhysicalObject)
SubClassOf(:side.n.wn.artifact soma:DependentPlace)
SubClassOf(:structure.n.wn.artifact dul:DesignedArtifact)
SubClassOf(:substance.n.wn.substance dul:Substance)
EquivalentClasses(:fluid.n.wn.substance soma:Fluid)
SubClassOf(:way.n.wn.artifact dul:DesignedArtifact)

SubClassOf(ObjectIntersectionOf(dul:Agent :body_part.n.wn.anatomy) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :beverage.n.wn.food) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :fabric.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :food.n.wn.food) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :instrumentality.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :object.n.wn.object) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :part.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :plant_part.n.wn.plant) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :region.n.wn.location) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :side.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :structure.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :substance.n.wn.substance) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:Agent :way.n.wn.artifact) owl:Nothing)

SubClassOf(ObjectIntersectionOf(dul:BiologicalObject :way.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:BiologicalObject :instrumentality.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:BiologicalObject :object.n.wn.object) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:BiologicalObject :region.n.wn.location) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:BiologicalObject :structure.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(dul:BiologicalObject :substance.n.wn.substance) owl:Nothing)

SubClassOf(ObjectIntersectionOf(:region.n.wn.location :fabric.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(:region.n.wn.location :beverage.n.wn.food) owl:Nothing)
SubClassOf(ObjectIntersectionOf(:region.n.wn.location :food.n.wn.food) owl:Nothing)
SubClassOf(ObjectIntersectionOf(:region.n.wn.location :instrumentality.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(:region.n.wn.location :part.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(:region.n.wn.location :side.n.wn.artifact) owl:Nothing)
SubClassOf(ObjectIntersectionOf(:region.n.wn.location :substance.n.wn.substance) owl:Nothing)

SubClassOf(:disposition.Actor :disposition.Agent)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Actor) ObjectSomeValuesFrom(dul:hasQuality :disposition.Actor))
SubClassOf(:disposition.Actor1 :disposition.Actor)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Actor1) ObjectSomeValuesFrom(dul:hasQuality :disposition.Actor1))
SubClassOf(:disposition.Actor2 :disposition.Actor)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Actor2) ObjectSomeValuesFrom(dul:hasQuality :disposition.Actor2))
SubClassOf(:disposition.Agent soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Agent) ObjectSomeValuesFrom(dul:hasQuality :disposition.Agent))
SubClassOf(:disposition.Asset soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Asset) ObjectSomeValuesFrom(dul:hasQuality :disposition.Asset))
SubClassOf(:disposition.Attribute soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Attribute) ObjectSomeValuesFrom(dul:hasQuality :disposition.Attribute))
SubClassOf(:disposition.Beneficiary soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Beneficiary) ObjectSomeValuesFrom(dul:hasQuality :disposition.Beneficiary))
SubClassOf(:disposition.Cause soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Cause) ObjectSomeValuesFrom(dul:hasQuality :disposition.Cause))
SubClassOf(:disposition.Destination :disposition.Location)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Destination) ObjectSomeValuesFrom(dul:hasQuality :disposition.Destination))
SubClassOf(:disposition.Experiencer :disposition.Agent)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Experiencer) ObjectSomeValuesFrom(dul:hasQuality :disposition.Experiencer))
SubClassOf(:disposition.Extent soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Extent) ObjectSomeValuesFrom(dul:hasQuality :disposition.Extent))
SubClassOf(:disposition.Instrument soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Instrument) ObjectSomeValuesFrom(dul:hasQuality :disposition.Instrument))
SubClassOf(:disposition.Location soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Location) ObjectSomeValuesFrom(dul:hasQuality :disposition.Location))
SubClassOf(:disposition.Material soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Material) ObjectSomeValuesFrom(dul:hasQuality :disposition.Material))
SubClassOf(:disposition.Patient soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Patient) ObjectSomeValuesFrom(dul:hasQuality :disposition.Patient))
SubClassOf(:disposition.Patient1 :disposition.Patient)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Patient1) ObjectSomeValuesFrom(dul:hasQuality :disposition.Patient1))
SubClassOf(:disposition.Patient2 :disposition.Patient)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Patient2) ObjectSomeValuesFrom(dul:hasQuality :disposition.Patient2))
SubClassOf(:disposition.Predicate soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Predicate) ObjectSomeValuesFrom(dul:hasQuality :disposition.Predicate))
SubClassOf(:disposition.Product soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Product) ObjectSomeValuesFrom(dul:hasQuality :disposition.Product))
SubClassOf(:disposition.Recipient soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Recipient) ObjectSomeValuesFrom(dul:hasQuality :disposition.Recipient))
SubClassOf(:disposition.Source :disposition.Location)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Source) ObjectSomeValuesFrom(dul:hasQuality :disposition.Source))
SubClassOf(:disposition.Stimulus soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Stimulus) ObjectSomeValuesFrom(dul:hasQuality :disposition.Stimulus))
SubClassOf(:disposition.Theme soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Theme) ObjectSomeValuesFrom(dul:hasQuality :disposition.Theme))
SubClassOf(:disposition.Theme1 :disposition.Theme)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Theme1) ObjectSomeValuesFrom(dul:hasQuality :disposition.Theme1))
SubClassOf(:disposition.Theme2 :disposition.Theme)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Theme2) ObjectSomeValuesFrom(dul:hasQuality :disposition.Theme2))
SubClassOf(:disposition.Time soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Time) ObjectSomeValuesFrom(dul:hasQuality :disposition.Time))
SubClassOf(:disposition.Topic soma:Disposition)
SubClassOf(ObjectSomeValuesFrom(dul:isClassifiedBy :Topic) ObjectSomeValuesFrom(dul:hasQuality :disposition.Topic))

# Has a :disposition.Attribute -> not physical object
SubClassOf(ObjectIntersectionOf(ObjectSomeValuesFrom(dul:hasQuality :disposition.Attribute) dul:PhysicalObject) owl:Nothing)
# Has a :disposition.Material -> physical substance, not instrumentality
SubClassOf(ObjectSomeValuesFrom(dul:hasQuality :disposition.Material) dul:Substance)
SubClassOf(ObjectIntersectionOf(ObjectSomeValuesFrom(dul:hasQuality :disposition.Material) :instrumentality.n.wn.artifact) owl:Nothing)
# Has a :disposition.Instrument -> instrumentality
SubClassOf(ObjectSomeValuesFrom(dul:hasQuality :disposition.Instrument) :instrumentality.n.wn.artifact)
# Has a :disposition.Predicate -> description
SubClassOf(ObjectSomeValuesFrom(dul:hasQuality :disposition.Predicate) dul:Description)
SubClassOf(ObjectSomeValuesFrom(dul:hasQuality :disposition.Agent) dul:Agent)

SubClassOf(ObjectIntersectionOf(:abstract dul:PhysicalObject) owl:Nothing)
EquivalentClasses(:animate dul:PhysicalAgent)
EquivalentClasses(:body_part :body_part.n.wn.anatomy)
EquivalentClasses(:comestible ObjectUnionOf(:beverage.n.wn.food :food.n.wn.food))
SubClassOf(:communication dul:InformationObject)
EquivalentClasses(:concrete dul:PhysicalObject)
SubClassOf(:currency dul:SocialObject)
SubClassOf(:elongated dul:PhysicalObject)
EquivalentClasses(:human :person.n.wn.body)
SubClassOf(:int_control dul:PhysicalAgent)
EquivalentClasses(:machine :machine.n.wn.artifact)
SubClassOf(:nonrigid dul:PhysicalObject)
SubClassOf(:organization dul:Organization)
EquivalentClasses(:plural dul:ObjectAggregate)
SubClassOf(:pointy dul:PhysicalObject)
SubClassOf(ObjectIntersectionOf(:scalar dul:PhysicalObject) owl:Nothing)
SubClassOf(:solid dul:PhysicalObject)
SubClassOf(ObjectIntersectionOf(:solid soma:Fluid) owl:Nothing)
EquivalentClasses(:substance dul:Substance)
SubClassOf(ObjectIntersectionOf(:time dul:PhysicalObject) owl:Nothing)
EquivalentClasses(:vehicle :vehicle.n.wn.artifact)


)
